* SO (SDL ObjectOriented)

** A *C++* wrapper around [[https://www.libsdl.org/][SDL]] cross-platform development library.

** Dependencies
   *SO* is intend to work with all *SDL2* major versions.
   Other libraries such as [[https://www.libsdl.org/projects/SDL_image/][SDL_image]] and [[https://www.libsdl.org/projects/SDL_ttf/][SDL_ttf]] work too.

** Build library
   To *build* the shared library, use *GNU make* utility.

** To install
   Use *sudo make install*.

   There's no configure file yet. If you don't want to use *SDL_image*,
   remove the *#include <SDL2/SDL_image.h>* macro in *SDL.hpp*, and
   remove *-lSDL2_image* in *LIBS* from *MakeFile*.

** Testings
   *SO* uses [[https://github.com/philsquared/Catch][Catch]] for its testing.

   To *run* tests, use *make tests*.

   To *create* tests, you simply have to create a *.cpp* file under the directory *tests/src*. 

** Documentation

   *SO* uses [[http://www.stack.nl/~dimitri/doxygen/][Doxygen]] to generate its documentation.

   To *generate* documentaion, use *make doc*.

** Namespace & function's name

   To make *SO* easier to use, every class wrapper use the (almost) same 
   documentation provided by the SDL's [[https://wiki.libsdl.org/][Wiki]].

   Every other none wrapper classes/functions offered by *SO* follow the exact same documentation style.
   Also, to ensure no name collision, everything is wrap in namespace *SO*.
   Finally, every name are /CamelCase/.

*** Examples

    *SDL_Window* -> *SO::Window*
 
    *SDL_GetWindowPosition* -> *SO::Window::getPosition*

    *SDL_Renderer* -> *SO::Renderer*

    *SDL_RenderSetScale* -> *SO::Renderer::setScale*

    Constants have also been re-written in *enum class*.

    *SDL_INIT_VIDEO* -> *SO::Init::Video*

    *SDL_WINDOW_FULLSCREEN* -> *SO::Window::FullScreen**

** Usage

#+BEGIN_SRC C++
  #include <SO/SDL.hpp>
  #include <SO/Window.hpp>
  #include <SO/Renderer.hpp>

  int main()
  {
    // Call to SDL_Init with flag SDL_INIT_VIDEO
    SO::init(SO::Init::Video);

    // Create a resizable window at position (0,0) of size (250, 250)
    SO::Window root("Minimal app", 0, 0, SO::Window::Resizable, 250, 250);

    // Create a hardware accelerated renderer, hooked to root
    SO::Renderer renderer(root, SO::Renderer::Accelerated);

    SO::Event event;

    bool quit = false;

    while (!quit)
    {
      // Events handler
      while (SO::PollEvent(event))
      {
        if (event.type == SDL_QUIT)
        {
          quit = false;
          break;
        }

        // Handle other events
      }

      // Do stuff 
    }  

    // Quit all subsystems
    SO::quit();

    return 0;
  }
#+END_SRC

** Others examples

   To see others examples, see my other repo [[https://github.com/lzrdkng/SO-Examples][SO-Examples]].
